In [1]:
!pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (3.7.1)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (1.22.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (4.39.3)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (3.0.9)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (5.12.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib) (1.4.4)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from importlib-resources>=3.2.0->matplotlib) (3.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [2]:
!pip install wordcloud

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wordcloud in /usr/local/lib/python3.9/dist-packages (1.8.2.2)
Requirement already satisfied: numpy>=1.6.1 in /usr/local/lib/python3.9/dist-packages (from wordcloud) (1.22.4)
Requirement already satisfied: pillow in /usr/local/lib/python3.9/dist-packages (from wordcloud) (8.4.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (from wordcloud) (3.7.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (23.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (1.0.7)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (5.12.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (4.39.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from importlib-resources>=3.2.0->matplotlib->wordcloud) (3.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)

In [5]:
import pandas as pd
import glob
import re
from functools import reduce
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from collections import Counter
import matplotlib.pyplot as plt
from wordcloud import STOPWORDS, WordCloud

nltk.download -> d 입력 -> all 입력

In [7]:
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all

    Downloading collection 'all'
       |
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger.zip.
       | Downloading package averaged_perceptron_tagger_ru to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger_ru.zip.
       | Downloading package basque_grammars to /root/nltk_data...
       |   Unzipping grammars/basque_grammars.zip.
       | Downloading package bcp47 to /root/nltk_data...
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package bllip_wsj_no_aux to /root/nltk_data...
       |   Unzipping models/bllip_wsj_no_aux.zip.
       | Downloading package book_grammars to /root/nltk_data...
       |   Unzipping grammars/book_grammars.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
       |   Unzipping corpora/cess_esp.zip.
       | Downloading package chat80 to /root/nltk_data...
       |   Unzipping corpora/chat80.zip.
       | Downloading package city_database to /root/nltk_data...
       |   Unzipping corpora/city_database.zip.
       | Downloading package cmudict to /root/nltk_data...
       |   Unzipping corpora/cmudict.zip.
       | Downloading package comparative_sentences to
       |     /root/nltk_data...
       |   Unzipping corpora/comparative_sentences.zip.
       | Downloading package comtrans to /root/nltk_data...
       | Downloading package conll2000 to /root/nltk_data...
       |   Unzipping corpora/conll2000.zip.
       | Downloading package conll2002 to /root/nltk_data...
       |   Unzipping corpora/conll2002.zip.
       | Downloading package conll2007 to /root/nltk_data...
       | Downloading package crubadan to /root/nltk_data...
       |   Unzipping corpora/crubadan.zip.
       | Downloading package dependency_treebank to /root/nltk_data...
       |   Unzipping corpora/dependency_treebank.zip.
       | Downloading package dolch to /root/nltk_data...
       |   Unzipping corpora/dolch.zip.
       | Downloading package europarl_raw to /root/nltk_data...
       |   Unzipping corpora/europarl_raw.zip.
       | Downloading package extended_omw to /root/nltk_data...
       | Downloading package floresta to /root/nltk_data...
       |   Unzipping corpora/floresta.zip.
       | Downloading package framenet_v15 to /root/nltk_data...
       |   Unzipping corpora/framenet_v15.zip.
       | Downloading package framenet_v17 to /root/nltk_data...
       |   Unzipping corpora/framenet_v17.zip.
       | Downloading package gazetteers to /root/nltk_data...
       |   Unzipping corpora/gazetteers.zip.
       | Downloading package genesis to /root/nltk_data...
       |   Unzipping corpora/genesis.zip.
       | Downloading package gutenberg to /root/nltk_data...
       |   Unzipping corpora/gutenberg.zip.
       | Downloading package ieer to /root/nltk_data...
       |   Unzipping corpora/ieer.zip.
       | Downloading package inaugural to /root/nltk_data...
       |   Unzipping corpora/inaugural.zip.
       | Downloading package indian to /root/nltk_data...
       |   Unzipping corpora/indian.zip.
       | Downloading package jeita to /root/nltk_data...
       | Downloading package kimmo to /root/nltk_data...
       |   Unzipping corpora/kimmo.zip.
       | Downloading package knbc to /root/nltk_data...
       | Downloading package large_grammars to /root/nltk_data...
       |   Unzipping grammars/large_grammars.zip.
       | Downloading package lin_thesaurus to /root/nltk_data...
       |   Unzipping corpora/lin_thesaurus.zip.
       | Downloading package mac_morpho to /root/nltk_data...
       |   Unzipping corpora/mac_morpho.zip.
       | Downloading package machado to /root/nltk_data...
       | Downloading package masc_tagged to /root/nltk_data...
       | Downloading package maxent_ne_chunker to /root/nltk_data...
       |   Unzipping chunkers/maxent_ne_chunker.zip.
       | Downloading package maxent_treebank_pos_tagger to
       |     /root/nltk_data...
       |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
       | Downloading package moses_sample to /root/nltk_data...
       |   Unzipping models/moses_sample.zip.
       | Downloading package movie_reviews to /root/nltk_data...
       |   Unzipping corpora/movie_reviews.zip.
       | Downloading package mte_teip5 to /root/nltk_data...
       |   Unzipping corpora/mte_teip5.zip.
       | Downloading package mwa_ppdb to /root/nltk_data...
       |   Unzipping misc/mwa_ppdb.zip.
       | Downloading package names to /root/nltk_data...
       |   Unzipping corpora/names.zip.
       | Downloading package nombank.1.0 to /root/nltk_data...
       | Downloading package nonbreaking_prefixes to
       |     /root/nltk_data...
       |   Unzipping corpora/nonbreaking_prefixes.zip.
       | Downloading package nps_chat to /root/nltk_data...
       |   Unzipping corpora/nps_chat.zip.
       | Downloading package omw to /root/nltk_data...
       | Downloading package omw-1.4 to /root/nltk_data...
       | Downloading package opinion_lexicon to /root/nltk_data...
       |   Unzipping corpora/opinion_lexicon.zip.
       | Downloading package panlex_swadesh to /root/nltk_data...
       | Downloading package paradigms to /root/nltk_data...
       |   Unzipping corpora/paradigms.zip.
       | Downloading package pe08 to /root/nltk_data...
       |   Unzipping corpora/pe08.zip.
       | Downloading package perluniprops to /root/nltk_data...
       |   Unzipping misc/perluniprops.zip.
       | Downloading package pil to /root/nltk_data...
       |   Unzipping corpora/pil.zip.
       | Downloading package pl196x to /root/nltk_data...
       |   Unzipping corpora/pl196x.zip.
       | Downloading package porter_test to /root/nltk_data...
       |   Unzipping stemmers/porter_test.zip.
       | Downloading package ppattach to /root/nltk_data...
       |   Unzipping corpora/ppattach.zip.
       | Downloading package problem_reports to /root/nltk_data...
       |   Unzipping corpora/problem_reports.zip.
       | Downloading package product_reviews_1 to /root/nltk_data...
       |   Unzipping corpora/product_reviews_1.zip.
       | Downloading package product_reviews_2 to /root/nltk_data...
       |   Unzipping corpora/product_reviews_2.zip.
       | Downloading package propbank to /root/nltk_data...
       | Downloading package pros_cons to /root/nltk_data...
       |   Unzipping corpora/pros_cons.zip.
       | Downloading package ptb to /root/nltk_data...
       |   Unzipping corpora/ptb.zip.
       | Downloading package punkt to /root/nltk_data...
       |   Unzipping tokenizers/punkt.zip.
       | Downloading package qc to /root/nltk_data...
       |   Unzipping corpora/qc.zip.
       | Downloading package reuters to /root/nltk_data...
       | Downloading package rslp to /root/nltk_data...
       |   Unzipping stemmers/rslp.zip.
       | Downloading package rte to /root/nltk_data...
       |   Unzipping corpora/rte.zip.
       | Downloading package sample_grammars to /root/nltk_data...
       |   Unzipping grammars/sample_grammars.zip.
       | Downloading package semcor to /root/nltk_data...
       | Downloading package senseval to /root/nltk_data...
       |   Unzipping corpora/senseval.zip.
       | Downloading package sentence_polarity to /root/nltk_data...
       |   Unzipping corpora/sentence_polarity.zip.
       | Downloading package sentiwordnet to /root/nltk_data...
       |   Unzipping corpora/sentiwordnet.zip.
       | Downloading package shakespeare to /root/nltk_data...
       |   Unzipping corpora/shakespeare.zip.
       | Downloading package sinica_treebank to /root/nltk_data...
       |   Unzipping corpora/sinica_treebank.zip.
       | Downloading package smultron to /root/nltk_data...
       |   Unzipping corpora/smultron.zip.
       | Downloading package snowball_data to /root/nltk_data...
       | Downloading package spanish_grammars to /root/nltk_data...
       |   Unzipping grammars/spanish_grammars.zip.
       | Downloading package state_union to /root/nltk_data...
       |   Unzipping corpora/state_union.zip.
       | Downloading package stopwords to /root/nltk_data...
       |   Unzipping corpora/stopwords.zip.
       | Downloading package subjectivity to /root/nltk_data...
       |   Unzipping corpora/subjectivity.zip.
       | Downloading package swadesh to /root/nltk_data...
       |   Unzipping corpora/swadesh.zip.
       | Downloading package switchboard to /root/nltk_data...
       |   Unzipping corpora/switchboard.zip.
       | Downloading package tagsets to /root/nltk_data...
       |   Unzipping help/tagsets.zip.
       | Downloading package timit to /root/nltk_data...
       |   Unzipping corpora/timit.zip.
       | Downloading package toolbox to /root/nltk_data...
       |   Unzipping corpora/toolbox.zip.
       | Downloading package treebank to /root/nltk_data...
       |   Unzipping corpora/treebank.zip.
       | Downloading package twitter_samples to /root/nltk_data...
       |   Unzipping corpora/twitter_samples.zip.
       | Downloading package udhr to /root/nltk_data...
       |   Unzipping corpora/udhr.zip.
       | Downloading package udhr2 to /root/nltk_data...
       |   Unzipping corpora/udhr2.zip.
       | Downloading package unicode_samples to /root/nltk_data...
       |   Unzipping corpora/unicode_samples.zip.
       | Downloading package universal_tagset to /root/nltk_data...
       |   Unzipping taggers/universal_tagset.zip.
       | Downloading package universal_treebanks_v20 to
       |     /root/nltk_data...
       | Downloading package vader_lexicon to /root/nltk_data...
       | Downloading package verbnet to /root/nltk_data...
       |   Unzipping corpora/verbnet.zip.
       | Downloading package verbnet3 to /root/nltk_data...
       |   Unzipping corpora/verbnet3.zip.
       | Downloading package webtext to /root/nltk_data...
       |   Unzipping corpora/webtext.zip.
       | Downloading package wmt15_eval to /root/nltk_data...
       |   Unzipping models/wmt15_eval.zip.
       | Downloading package word2vec_sample to /root/nltk_data...
       |   Unzipping models/word2vec_sample.zip.
       | Downloading package wordnet to /root/nltk_data...
       | Downloading package wordnet2021 to /root/nltk_data...
       | Downloading package wordnet2022 to /root/nltk_data...
       |   Unzipping corpora/wordnet2022.zip.
       | Downloading package wordnet31 to /root/nltk_data...
       | Downloading package wordnet_ic to /root/nltk_data...
       |   Unzipping corpora/wordnet_ic.zip.
       | Downloading package words to /root/nltk_data...
       |   Unzipping corpora/words.zip.
       | Downloading package ycoe to /root/nltk_data...
       |   Unzipping corpora/ycoe.zip.
       |
     Done downloading collection all

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q

True

In [6]:
all_files = glob.glob('myCabinetExcelData*.xls')
all_files

['myCabinetExcelData (1).xls',
 'myCabinetExcelData (7).xls',
 'myCabinetExcelData (2).xls',
 'myCabinetExcelData (5).xls',
 'myCabinetExcelData (4).xls',
 'myCabinetExcelData (6).xls',
 'myCabinetExcelData (9).xls',
 'myCabinetExcelData (8).xls',
 'myCabinetExcelData (3).xls',
 'myCabinetExcelData.xls']

In [8]:
all_files_data = []
for file in all_files:
  data_frame = pd.read_excel(file)
  all_files_data.append(data_frame)
all_files_data[0]

,Unnamed: 0,번호,제목,저자,출판사,출판일
0,NaN,1,A big-data analytics method for capturing visi...,"Miah, Shah Jahan; Vu, HuyQuan; Gammack, John",Springer Nature,2019
1,NaN,2,Ecology Big-data approaches lead to an increas...,"Nathan, R.",AMERICAN ASSOCIATION FOR THE ADVANCEMENT OF SC...,2022
2,NaN,3,A Big-Data Analysis of Disaster Information Di...,"Hwang, Yongsuk; Jeong, Jaekwan; Jin, Eun-Hyeon...",Springer,2018
3,NaN,4,Real-world big-data studies in laboratory medi...,"Ma, Chaochao; Wang, Xinlu; Wu, Jie; Cheng, Xin...","Elsevier Science B.V., Amsterdam.",2020
4,NaN,5,Der Big-Data-Kunde,unknown,VERLAGSGRUPPE HANDELSBLATT,2017
...,...,...,...,...,...,...
95,NaN,96,Interview mit Michael Feindt zum Thema „Präskr...,"Jarke, M.",unknown,2014
96,NaN,97,RW4 APPLICATION OF ARTIFICIAL INTELLIGENCE AND...,"Xiong, T.; Li, J.; Hao, Y.; Xu, J.","Elsevier Science B.V., Amsterdam",2019
97,NaN,98,"„Wichtig ist auch der Hinweis, dass Big-Data- ...",unknown,Springer Science + Business Media,2016
98,NaN,99,"Symposium on insure‐tech, digitalization, and ...","Bauer, Daniel; Tyler Leverty, James; Schmit, J...",Wiley-Blackwell,2021
99,NaN,100,In sieben Schritten zum erfolgreichen Big-Data...,"Conrads, R.",Springer Science + Business Media,2014

In [9]:
all_files_data_concat = pd.concat(all_files_data, axis = 0, ignore_index = True)
all_files_data_concat

,Unnamed: 0,번호,제목,저자,출판사,출판일
0,NaN,1,A big-data analytics method for capturing visi...,"Miah, Shah Jahan; Vu, HuyQuan; Gammack, John",Springer Nature,2019
1,NaN,2,Ecology Big-data approaches lead to an increas...,"Nathan, R.",AMERICAN ASSOCIATION FOR THE ADVANCEMENT OF SC...,2022
2,NaN,3,A Big-Data Analysis of Disaster Information Di...,"Hwang, Yongsuk; Jeong, Jaekwan; Jin, Eun-Hyeon...",Springer,2018
3,NaN,4,Real-world big-data studies in laboratory medi...,"Ma, Chaochao; Wang, Xinlu; Wu, Jie; Cheng, Xin...","Elsevier Science B.V., Amsterdam.",2020
4,NaN,5,Der Big-Data-Kunde,unknown,VERLAGSGRUPPE HANDELSBLATT,2017
...,...,...,...,...,...,...
995,NaN,96,Distributed Big-Data Optimization via Blockwis...,"Notarnicola, Ivano; Sun, Ying; Scutari, Gesual...",IEEE INSTITUTE OF ELECTRICAL AND ELECTRONICS,2021
996,NaN,97,A big-data analysis of political rhetoric rela...,"Carter, Patrick; Wang, Jeffrie; Chau, Davis",Emerald Publishing,2020
997,NaN,98,Streetlytics: Big-Data for Real Estate Market ...,"Thrall, Grant",unknown,2015
998,NaN,99,On-Line Big-Data Processing for Visual Analyti...,"Vlantis, Panayiotis I.; Delis, Alex",Springer,2018
999,NaN,100,Becoming data-savvy in a big-data world,"Xu, Meng; Rhee, Seung Yon","Elsevier Science B.V., Amsterdam.",2014

In [10]:
all_files_data_concat.to_csv('riss_bigdata.csv', encoding = 'utf-8', index = False)

In [11]:
all_title = all_files_data_concat['제목']
all_title

0      A big-data analytics method for capturing visi...
1      Ecology Big-data approaches lead to an increas...
2      A Big-Data Analysis of Disaster Information Di...
3      Real-world big-data studies in laboratory medi...
4                                     Der Big-Data-Kunde
                             ...
995    Distributed Big-Data Optimization via Blockwis...
996    A big-data analysis of political rhetoric rela...
997    Streetlytics: Big-Data for Real Estate Market ...
998    On-Line Big-Data Processing for Visual Analyti...
999              Becoming data-savvy in a big-data world
Name: 제목, Length: 1000, dtype: object

In [12]:
stopWords = set(stopwords.words("english"))
lemma = WordNetLemmatizer()

In [14]:
words = []

for title in all_title:
  EnWords = re.sub(r"[^a-zA-Z]+", " ", str(title))
  EnWordsToken = word_tokenize(EnWords.lower())
  EnWordsTokenStop = [w for w in EnWordsToken if w not in stopWords]
  EnWordsTokenStopLemma = [lemma.lemmatize(w) for w in EnWordsTokenStop]
  words.append(EnWordsTokenStopLemma)

In [15]:
print(words)

[['big', 'data', 'analytics', 'method', 'capturing', 'visitor', 'activity', 'flow', 'case', 'island', 'country'], ['ecology', 'big', 'data', 'approach', 'lead', 'increased', 'understanding', 'ecology', 'animal', 'movement'], ['big', 'data', 'analysis', 'disaster', 'information', 'dissemination', 'south', 'korea'], ['real', 'world', 'big', 'data', 'study', 'laboratory', 'medicine', 'current', 'status', 'application', 'future', 'consideration'], ['der', 'big', 'data', 'kunde'], ['clinical', 'big', 'data', 'based', 'design', 'glut', 'targeted', 'carbon', 'nanodots', 'accurate', 'diagnosis', 'hepatocellular', 'carcinomaelectronic', 'supplementary', 'information', 'esi', 'available', 'see', 'doi', 'http', 'doi', 'org', 'nr', 'j'], ['mandola', 'big', 'data', 'processing', 'visualization', 'platform', 'monitoring', 'detecting', 'online', 'hate', 'speech'], ['cloud', 'big', 'data', 'driven', 'dynamic', 'control', 'approach', 'unmanned', 'ground', 'vehicle', 'safety', 'improving'], ['distributed', 'partitioned', 'big', 'data', 'optimization', 'via', 'asynchronous', 'dual', 'decomposition'], ['tensor', 'based', 'big', 'data', 'driven', 'routing', 'recommendation', 'approach', 'heterogeneous', 'network'], ['leveraging', 'big', 'data', 'revolution', 'cm', 'expanding', 'capability', 'spur', 'health', 'system', 'transformation'], ['editorial', 'advanced', 'big', 'data', 'analysis', 'method', 'tool', 'high', 'throughput', 'omics', 'technology'], ['four', 'health', 'data', 'network', 'illustrate', 'potential', 'shared', 'national', 'multipurpose', 'big', 'data', 'network'], ['ibm', 'stellt', 'big', 'data', 'service', 'au', 'twitter', 'vor'], ['traditional', 'v', 'big', 'data', 'fashion', 'trend', 'forecasting', 'examination', 'using', 'wgsn', 'edited'], ['optimizing', 'read', 'data', 'flow', 'big', 'data', 'application'], ['enlightenment', 'big', 'data', 'era', 'clinical', 'research', 'tcm', 'acupuncture'], ['comprehensive', 'big', 'data', 'based', 'monitoring', 'system', 'yield', 'enhancement', 'semiconductor', 'manufacturing'], ['genomics', 'big', 'data', 'precision', 'medicine'], ['lesson', 'big', 'data', 'project'], ['hybrid', 'big', 'data', 'based', 'tolerance', 'based', 'method', 'estimate', 'environmental', 'benefit', 'electric', 'bike', 'sharing'], ['st', 'century', 'investing', 'big', 'data', 'company', 'soaring', 'despite', 'high', 'price', 'still', 'possible', 'cash'], ['proactive', 'manufacturing', 'big', 'data', 'driven', 'emerging', 'manufacturing', 'paradigm'], ['research', 'big', 'data', 'mining', 'visualization', 'application'], ['vermeidern', 'verringern', 'verbessern', 'big', 'data', 'analysen', 'al', 'alternative', 'zu', 'tierversuchen'], ['simd', 'parallel', 'mcmc', 'sampling', 'application', 'big', 'data', 'bayesian', 'analytics'], ['integrative', 'biology', 'big', 'data', 'centrism', 'mapping', 'bioscience', 'ethic', 'perspective', 'w', 'matrix'], ['pmu', 'application', 'real', 'world', 'data', 'medical', 'big', 'data', 'platform', 'real', 'world', 'evidence', 'generation', 'practice', 'post', 'marketing', 'research', 'china'], ['design', 'implementation', 'big', 'data', 'analysis', 'application', 'spark', 'distribution', 'network', 'based', 'data', 'interception'], ['high', 'performance', 'solution', 'big', 'data', 'gwas'], ['point', 'intelligenz', 'contra', 'big', 'data', 'chaos'], ['framework', 'aligning', 'big', 'data', 'strategy', 'organizational', 'goal'], ['career', 'graduate', 'program', 'big', 'data', 'analyst'], ['high', 'availability', 'big', 'geo', 'data', 'platform', 'service'], ['computing', 'cloud', 'cover', 'big', 'data', 'era', 'putting', 'pressure', 'storage', 'method'], ['israeli', 'firm', 'medaware', 'offer', 'big', 'data', 'software', 'help', 'detect', 'prescription', 'error'], ['analysis', 'big', 'data', 'science', 'backwards'], ['methodology', 'real', 'time', 'data', 'sustainability', 'smart', 'city', 'towards', 'inferencing', 'analytics', 'big', 'data'], ['daten', 'und', 'diabetes', 'big', 'data', 'medizin'], ['conex', 'efficient', 'exploration', 'big', 'data', 'system', 'configuration', 'better', 'performance'], ['smallholder', 'need', 'access', 'big', 'data', 'agronomy'], ['jbhi', 'special', 'issue', 'big', 'data', 'health'], ['risk', 'reward', 'big', 'data', 'epigenomics', 'research', 'interview', 'melanie', 'ehrlich'], ['ultralow', 'power', 'memory', 'based', 'big', 'data', 'computing', 'platform', 'nonvolatile', 'domain', 'wall', 'nanowire', 'device'], ['bike', 'sharing', 'system', 'big', 'data', 'perspective'], ['facebook', 'fiasco', 'big', 'data', 'researcher', 'rethink', 'ethic'], ['mobile', 'edge', 'computing', 'big', 'data', 'enabled', 'electric', 'vehicle', 'charging'], ['comparative', 'evaluation', 'big', 'data', 'system', 'scientific', 'image', 'analytics', 'workload'], ['research', 'big', 'data', 'oriented', 'cloud', 'evaluation', 'complex', 'alliance', 'new', 'energy', 'vehicle'], ['political', 'depression', 'big', 'data', 'multimethod', 'investigation', 'american', 'emotional', 'response', 'trump', 'presidency'], ['selbst', 'ist', 'der', 'forscher', 'big', 'data', 'analysen', 'mit', 'galaxy'], ['semantic', 'interoperability', 'big', 'data', 'scale', 'open', 'opc', 'ua', 'implementation'], ['semantic', 'interoperability', 'big', 'data', 'heterogeneous', 'iot', 'infrastructure', 'healthcare'], ['performance', 'evaluation', 'nosql', 'big', 'data', 'application', 'using', 'multi', 'formalism', 'model'], ['da', 'grosse', 'datenproblem', 'big', 'data', 'analysen', 'zur', 'strategischen', 'unternehmensausrichtung'], ['abnormal', 'operation', 'tracking', 'big', 'data', 'based', 'gram', 'schmidt', 'orthogonalization', 'production', 'n', 'propyl', 'propionate', 'simulated', 'moving', 'bed', 'reactor', 'case', 'study'], ['formal', 'method', 'artificial', 'intelligence', 'big', 'data', 'analytics', 'knowledge', 'engineering', 'medical', 'care', 'reduce', 'disease', 'burden', 'health', 'disparity'], ['noch', 'verlaufen', 'die', 'big', 'data', 'analytics', 'projekte', 'ganz', 'anders', 'al', 'geplant'], ['enhancing', 'physical', 'layer', 'security', 'via', 'big', 'data', 'aided', 'hybrid', 'relay', 'selection'], ['buzzterm', 'boardroom', 'big', 'data', 'analytics', 'come'], ['middleware', 'managing', 'big', 'data', 'flow'], ['ari', 'caroline', 'big', 'data', 'guru', 'mine', 'analytics', 'help', 'cancer', 'patient', 'resource', 'career'], ['new', 'pattern', 'lifecycle', 'big', 'data', 'driven', 'smart', 'manufacturing', 'service', 'complex', 'product'], ['human', 'project', 'big', 'data', 'studie', 'startet', 'new', 'york'], ['situating', 'ecology', 'big', 'data', 'science', 'current', 'advance', 'challenge', 'solution'], ['brief', 'announcement', 'mending', 'big', 'data', 'missing', 'information'], ['advancing', 'manufacturing', 'system', 'big', 'data', 'analytics', 'conceptual', 'framework'], ['review', 'sentiment', 'discovery', 'analysis', 'educational', 'big', 'data'], ['industrial', 'symbiosis', 'exploring', 'big', 'data', 'approach', 'waste', 'stream', 'discovery'], ['pipelined', 'multi', 'gpu', 'mapreduce', 'big', 'data', 'processing'], ['accountability', 'big', 'data', 'algorithm'], ['noch', 'verlaufen', 'die', 'big', 'data', 'analytics', 'projekte', 'ganz', 'anders', 'al', 'geplant'], ['editorial', 'note', 'hci', 'system', 'big', 'data', 'based', 'multimedia', 'application'], ['emergency', 'drug', 'procurement', 'planning', 'based', 'big', 'data', 'driven', 'morbidity', 'prediction'], ['interview', 'mit', 'stefan', 'wrobel', 'zum', 'thema', 'angewandte', 'big', 'data', 'forschung'], ['physical', 'education', 'grand', 'convergence', 'fitnessgram', 'big', 'data', 'digital', 'commerce', 'child', 'health'], ['deadline', 'aware', 'scheduling', 'flexible', 'bandwidth', 'allocation', 'big', 'data', 'transfer'], ['ad', 'exec', 'future', 'big', 'data', 'draper'], ['qualitative', 'readiness', 'requirement', 'assessment', 'model', 'enterprise', 'big', 'data', 'infrastructure', 'investment'], ['position', 'synchronization', 'track', 'geometry', 'inspection', 'data', 'via', 'big', 'data', 'fusion', 'incremental', 'learning'], ['structural', 'health', 'monitoring', 'big', 'data', 'problem'], ['economics', 'econophysics', 'era', 'big', 'data'], ['identifying', 'industrial', 'cluster', 'novel', 'big', 'data', 'methodology', 'sic', 'code', 'fit', 'purpose', 'internet', 'age'], ['mapping', 'collective', 'behavior', 'big', 'data', 'era'], ['code', 'offloading', 'scheme', 'big', 'data', 'processing', 'android', 'application'], ['high', 'performance', 'interconnection', 'network', 'exascale', 'big', 'data', 'era'], ['power', 'message', 'network', 'big', 'data', 'analysis', 'network', 'agenda', 'setting', 'model', 'issue', 'ownership'], ['failure', 'analysis', 'prediction', 'big', 'data', 'system'], ['linear', 'estimation', 'problem', 'information', 'big', 'data', 'system'], ['phylogenomics', 'principle', 'opportunity', 'pitfall', 'big', 'data', 'phylogenetics'], ['kernel', 'based', 'framework', 'medical', 'big', 'data', 'analytics'], ['fast', 'algorithm', 'relaxation', 'process', 'big', 'data', 'system', 'page'], ['biology', 'must', 'develop', 'big', 'data', 'system'], ['jbhi', 'special', 'issue', 'x', 'c', 'big', 'data', 'health', 'x'], ['starting', 'think', 'big', 'data', 'approach', 'clinical', 'detection', 'early', 'stage', 'bipolar', 'disorder', 'evidence', 'based', 'assessment', 'statistical', 'learning', 'model'], ['interview', 'mit', 'michael', 'feindt', 'zum', 'thema', 'pr', 'skriptive', 'big', 'data', 'analyse'], ['rw', 'application', 'artificial', 'intelligence', 'medical', 'big', 'data', 'real', 'world', 'evidence', 'generation', 'literature', 'review', 'research', 'practice', 'china'], ['wichtig', 'ist', 'auch', 'der', 'hinweis', 'das', 'big', 'data', 'und', 'vergleichbare', 'konzepte', 'nicht', 'unmittelbar', 'greifen'], ['symposium', 'insure', 'tech', 'digitalization', 'big', 'data', 'technique', 'risk', 'management', 'insurance'], ['sieben', 'schritten', 'zum', 'erfolgreichen', 'big', 'data', 'projekt'], ['big', 'data', 'big', 'opportunity', 'librarian'], ['big', 'data', 'expert', 'discus', 'customer', 'data', 'treatment'], ['big', 'data', 'present', 'future'], ['big', 'data', 'driven', 'service', 'composition', 'using', 'parallel', 'clustered', 'particle', 'swarm', 'optimization', 'mobile', 'environment'], ['big', 'data', 'element', 'good', 'question', 'open', 'data', 'powerful', 'software'], ['big', 'data', 'hot', 'air', 'hot', 'topic'], ['big', 'data', 'web', 'crawling', 'analysing', 'financial', 'news', 'using', 'rapidminer'], ['big', 'data', 'whole', 'yotta', 'byte'], ['big', 'data', 'impact', 'u', 'medical', 'industry'], ['big', 'data', 'impact', 'trading', 'technology'], ['big', 'data', 'web', 'crawling', 'analysing', 'financial', 'news', 'using', 'rapidminer'], ['big', 'data', 'boon', 'business', 'intelligence'], ['big', 'data', 'key', 'energy', 'efficiency', 'smart', 'building'], ['big', 'data', 'implication', 'health', 'system', 'pharmacy'], ['big', 'data', 'driven', 'strategic', 'orientation', 'international', 'marketing'], ['data', 'asset', 'oil', 'gas', 'sector', 'learn', 'industry', 'big', 'data'], ['big', 'data', 'trend', 'stroke', 'epidemiology', 'united', 'state', 'good', 'data'], ['big', 'data', 'goldmine', 'minefield'], ['big', 'data', 'driven', 'manufacturing', 'process', 'monitoring', 'quality', 'philosophy'], ['big', 'data', 'breaking', 'new', 'ground', 'airway', 'research'], ['big', 'data', 'f', 'r', 'einen', 'ordnungsrahmen', 'zur', 'nutzung', 'digitaler', 'gesundheitsdaten', 'pl', 'diert', 'die', 'bundes', 'rztekammer'], ['big', 'data', 'revolution', 'oder', 'datenhybris'], ['big', 'data', 'critical', 'question', 'sport', 'society'], ['big', 'data', 'big', 'opportunity', 'petroleum', 'petrochemical', 'industry'], ['big', 'data', 'guest', 'editorial'], ['big', 'data', 'role', 'expanding', 'access', 'financial', 'service', 'china'], ['biomedical', 'big', 'data', 'new', 'model', 'control', 'access', 'use', 'governance'], ['spatiotemporal', 'data', 'adaptive', 'clustering', 'algorithm', 'intelligent', 'computational', 'technique', 'city', 'big', 'data'], ['data', 'aware', 'remote', 'procedure', 'call', 'method', 'big', 'data', 'system'], ['covid', 'big', 'data', 'change', 'way', 'practice', 'medicine'], ['rethinking', 'data', 'driven', 'decision', 'support', 'flood', 'risk', 'management', 'big', 'data', 'age'], ['finance', 'big', 'data', 'management', 'analysis', 'application'], ['using', 'big', 'data', 'guide', 'implementation', 'web', 'mobile', 'adaptive', 'learning', 'platform', 'medical', 'student'], ['big', 'data', 'driven', 'hr', 'practice', 'improve', 'hr', 'service', 'quality', 'innovation', 'competency', 'smes'], ['wie', 'big', 'data', 'auf', 'die', 'verkettung', 'von', 'strom', 'und', 'wasser', 'durchschlagen'], ['prescription', 'data', 'australia', 'useful', 'big', 'data'], ['using', 'big', 'data', 'optimally', 'model', 'hydrology', 'water', 'quality', 'across', 'expansive', 'region'], ['confronting', 'big', 'data', 'applying', 'confrontation', 'clause', 'government', 'data', 'collection'], ['modeling', 'big', 'data', 'based', 'system', 'ontological', 'trading'], ['big', 'data', 'smart', 'data', 'algorithm', 'cross', 'evaluation', 'novel', 'method', 'large', 'scale', 'survey', 'analysis'], ['taming', 'big', 'data', 'implementation', 'clinical', 'use', 'case', 'driven', 'architecture'], ['big', 'picture', 'big', 'data'], ['big', 'data', 'approach', 'global', 'freshwater', 'mussel', 'diversity', 'bivalvia', 'unionoida', 'updated', 'checklist', 'genus', 'specie'], ['using', 'big', 'data', 'co', 'innovation', 'process', 'mapping', 'field', 'data', 'driven', 'innovation', 'proposing', 'theoretical', 'development', 'providing', 'research', 'agenda'], ['big', 'data', 'centric', 'architecture', 'metamodel', 'industry'], ['medical', 'big', 'data', 'current', 'status', 'problem', 'trend', 'toward', 'solution'], ['exploring', 'big', 'data', 'next', 'big', 'thing', 'innovation'], ['digitisation', 'big', 'data', 'transformation', 'accounting', 'information'], ['integrating', 'big', 'data', 'surgical', 'practice'], ['scholarly', 'big', 'data', 'information', 'extraction', 'data', 'mining'], ['rethinking', 'big', 'data', 'visual', 'knowledge', 'sublime', 'diagrammatic', 'data', 'visualisation'], ['querying', 'big', 'data', 'bridging', 'theory', 'practice'], ['big', 'data', 'enabled', 'consolidated', 'framework', 'energy', 'efficient', 'software', 'defined', 'data', 'center', 'iot', 'setup'], ['humanizing', 'big', 'data', 'marketing', 'meeting', 'data', 'social', 'science', 'consumer', 'insightc', 'strong', 'london', 'kogan', 'page', 'pp', 'isbn'], ['regulating', 'big', 'data', 'guideline', 'council', 'europe', 'context', 'european', 'data', 'protection', 'framework'], ['big', 'data', 'business', 'strategy', 'interconnection', 'grand', 'challenge', 'knowledge', 'management', 'review', 'future', 'perspective'], ['marine', 'big', 'data', 'concept', 'application', 'platform', 'construction'], ['beyond', 'big', 'data', 'surveillance', 'metadata', 'technology', 'enabled', 'intelligence', 'opportunity', 'counter', 'terrorism'], ['big', 'data', 'state', 'mind', 'epistemological', 'challenge', 'accountability', 'transparency', 'data', 'driven', 'regulation'], ['rethink', 'big', 'european', 'roadmap', 'hardware', 'networking', 'optimization', 'big', 'data'], ['rethinking', 'big', 'data', 'visual', 'knowledge', 'sublime', 'diagrammatic', 'data', 'visualisation'], ['integrating', 'big', 'data', 'semantic', 'extract', 'transform', 'load', 'framework'], ['big', 'data', 'based', 'worker', 'behavior', 'observation', 'china', 'metro', 'construction'], ['coping', 'big', 'data', 'growing', 'pain'], ['digitisation', 'big', 'data', 'transformation', 'accounting', 'information'], ['big', 'data', 'approach', 'global', 'freshwater', 'mussel', 'diversity', 'bivalvia', 'unionoida', 'updated', 'checklist', 'genus', 'specie'], ['open', 'data', 'prevent', 'research', 'fraud', 'promote', 'reproducibility', 'enable', 'big', 'data', 'analytics', 'clinical', 'research'], ['harnessing', 'big', 'data', 'capability', 'deliver', 'result'], ['feedback', 'big', 'data', 'based', 'lie', 'robot'], ['integrating', 'big', 'data', 'surgical', 'practice'], ['data', 'driven', 'ax', 'creation', 'model', 'correlation', 'measurement', 'big', 'data', 'analytics'], ['embracing', 'big', 'data'], ['redefining', 'big', 'data', 'interview', 'bill', 'inmon'], ['big', 'data', 'smart', 'data', 'role', 'metabolomics', 'generating', 'actionable', 'knowledge', 'alzheimer', 'disease', 'personalized', 'treatment'], ['educational', 'big', 'data', 'extracting', 'meaning', 'data', 'smart', 'education'], ['big', 'data', 'make', 'big', 'impact', 'finding', 'systematic', 'review', 'longitudinal', 'case', 'study'], ['geospatial', 'big', 'data', 'new', 'paradigm', 'remote', 'sensing', 'application'], ['big', 'data', 'study', 'quantify', 'relationship', 'bmi', 'different', 'cancer'], ['big', 'data', 'embedded', 'new', 'product', 'development', 'influence', 'project', 'success'], ['harnessing', 'big', 'data', 'methodological', 'approach', 'linking', 'electronic', 'health', 'record', 'patient', 'reported', 'survey', 'data'], ['taming', 'big', 'data', 'applying', 'experimental', 'method', 'naturalistic', 'data', 'set'], ['architecting', 'big', 'data', 'challenge', 'study', 'forecast'], ['managing', 'big', 'data', 'cloud', 'computing', 'co', 'location', 'center'], ['integrating', 'big', 'data', 'aquatic', 'ecology', 'challenge', 'opportunity'], ['small', 'data', 'enabled', 'prediction', 'obama', 'win', 'say', 'economist', 'big', 'data', 'crowdsourcing', 'resulted', 'complex', 'prediction'], ['integrating', 'big', 'data', 'analytics', 'supply', 'chain', 'finance', 'role', 'information', 'processing', 'data', 'driven', 'culture'], ['big', 'data', 'content', 'delivery', 'wireless', 'device', 'device', 'sharing', 'large', 'scale', 'mobile', 'network'], ['bigger', 'data', 'big', 'data', 'twitter', 'brain', 'computer', 'interface'], ['big', 'data', 'rich', 'data', 'key', 'feature', 'athlete', 'wheelchair', 'mobility', 'performance'], ['prescription', 'data', 'australia', 'useful', 'big', 'data'], ['solving', 'big', 'data', 'distributing', 'computation', 'among', 'smart', 'device'], ['teaching', 'big', 'data', 'analysis', 'young', 'immunologist'], ['demystifying', 'big', 'data', 'mandatory', 'evolution', 'forensic', 'accounting', 'brazil'], ['using', 'data', 'driven', 'safety', 'decision', 'making', 'realize', 'smart', 'safety', 'management', 'era', 'big', 'data', 'theoretical', 'perspective', 'basic', 'question', 'answer'], ['using', 'big', 'data', 'cost', 'effectiveness', 'analysis', 'next', 'generation', 'sequencing', 'technology', 'challenge', 'potential', 'solution'], ['technology', 'big', 'data', 'search', 'benefit', 'making', 'insight', 'actionable', 'key'], ['mining', 'big', 'data', 'philologist', 'perspective'], ['aviation', 'community', 'beginning', 'understand', 'done', 'aircraft', 'big', 'data'], ['mobile', 'big', 'data', 'fuel', 'data', 'driven', 'wireless'], ['smart', 'evac', 'big', 'data', 'based', 'decision', 'making', 'emergency', 'evacuation'], ['bitkom', 'beste', 'voraussetzungen', 'f', 'r', 'den', 'big', 'data', 'standort', 'deutschland'], ['memory', 'tsvd', 'big', 'data', 'factorization'], ['fine', 'grained', 'dynamic', 'resource', 'allocation', 'big', 'data', 'application'], ['timed', 'analysis', 'big', 'data', 'application'], ['evaluation', 'eines', 'zukunftsszenarios', 'zur', 'nutzung', 'von', 'big', 'data', 'anwendungen', 'f', 'r', 'die', 'verbesserung', 'der', 'versorgung', 'von', 'menschen', 'mit', 'seltenen', 'erkrankungen'], ['monsanto', 'throw', 'hat', 'big', 'data', 'ring'], ['ursachenforschung', 'der', 'medizin', 'mit', 'big', 'data', 'dem', 'vergessen', 'auf', 'der', 'spur'], ['seeking', 'alpha', 'dividend', 'announcement', 'big', 'data', 'insight', 'joining', 'car', 'eva', 'style', 'analysis'], ['randomized', 

In [17]:
words2 = list(reduce(lambda x, y : x+y, words))
print(words2)

['big', 'data', 'analytics', 'method', 'capturing', 'visitor', 'activity', 'flow', 'case', 'island', 'country', 'ecology', 'big', 'data', 'approach', 'lead', 'increased', 'understanding', 'ecology', 'animal', 'movement', 'big', 'data', 'analysis', 'disaster', 'information', 'dissemination', 'south', 'korea', 'real', 'world', 'big', 'data', 'study', 'laboratory', 'medicine', 'current', 'status', 'application', 'future', 'consideration', 'der', 'big', 'data', 'kunde', 'clinical', 'big', 'data', 'based', 'design', 'glut', 'targeted', 'carbon', 'nanodots', 'accurate', 'diagnosis', 'hepatocellular', 'carcinomaelectronic', 'supplementary', 'information', 'esi', 'available', 'see', 'doi', 'http', 'doi', 'org', 'nr', 'j', 'mandola', 'big', 'data', 'processing', 'visualization', 'platform', 'monitoring', 'detecting', 'online', 'hate', 'speech', 'cloud', 'big', 'data', 'driven', 'dynamic', 'control', 'approach', 'unmanned', 'ground', 'vehicle', 'safety', 'improving', 'distributed', 'partitioned', 'big', 'data', 'optimization', 'via', 'asynchronous', 'dual', 'decomposition', 'tensor', 'based', 'big', 'data', 'driven', 'routing', 'recommendation', 'approach', 'heterogeneous', 'network', 'leveraging', 'big', 'data', 'revolution', 'cm', 'expanding', 'capability', 'spur', 'health', 'system', 'transformation', 'editorial', 'advanced', 'big', 'data', 'analysis', 'method', 'tool', 'high', 'throughput', 'omics', 'technology', 'four', 'health', 'data', 'network', 'illustrate', 'potential', 'shared', 'national', 'multipurpose', 'big', 'data', 'network', 'ibm', 'stellt', 'big', 'data', 'service', 'au', 'twitter', 'vor', 'traditional', 'v', 'big', 'data', 'fashion', 'trend', 'forecasting', 'examination', 'using', 'wgsn', 'edited', 'optimizing', 'read', 'data', 'flow', 'big', 'data', 'application', 'enlightenment', 'big', 'data', 'era', 'clinical', 'research', 'tcm', 'acupuncture', 'comprehensive', 'big', 'data', 'based', 'monitoring', 'system', 'yield', 'enhancement', 'semiconductor', 'manufacturing', 'genomics', 'big', 'data', 'precision', 'medicine', 'lesson', 'big', 'data', 'project', 'hybrid', 'big', 'data', 'based', 'tolerance', 'based', 'method', 'estimate', 'environmental', 'benefit', 'electric', 'bike', 'sharing', 'st', 'century', 'investing', 'big', 'data', 'company', 'soaring', 'despite', 'high', 'price', 'still', 'possible', 'cash', 'proactive', 'manufacturing', 'big', 'data', 'driven', 'emerging', 'manufacturing', 'paradigm', 'research', 'big', 'data', 'mining', 'visualization', 'application', 'vermeidern', 'verringern', 'verbessern', 'big', 'data', 'analysen', 'al', 'alternative', 'zu', 'tierversuchen', 'simd', 'parallel', 'mcmc', 'sampling', 'application', 'big', 'data', 'bayesian', 'analytics', 'integrative', 'biology', 'big', 'data', 'centrism', 'mapping', 'bioscience', 'ethic', 'perspective', 'w', 'matrix', 'pmu', 'application', 'real', 'world', 'data', 'medical', 'big', 'data', 'platform', 'real', 'world', 'evidence', 'generation', 'practice', 'post', 'marketing', 'research', 'china', 'design', 'implementation', 'big', 'data', 'analysis', 'application', 'spark', 'distribution', 'network', 'based', 'data', 'interception', 'high', 'performance', 'solution', 'big', 'data', 'gwas', 'point', 'intelligenz', 'contra', 'big', 'data', 'chaos', 'framework', 'aligning', 'big', 'data', 'strategy', 'organizational', 'goal', 'career', 'graduate', 'program', 'big', 'data', 'analyst', 'high', 'availability', 'big', 'geo', 'data', 'platform', 'service', 'computing', 'cloud', 'cover', 'big', 'data', 'era', 'putting', 'pressure', 'storage', 'method', 'israeli', 'firm', 'medaware', 'offer', 'big', 'data', 'software', 'help', 'detect', 'prescription', 'error', 'analysis', 'big', 'data', 'science', 'backwards', 'methodology', 'real', 'time', 'data', 'sustainability', 'smart', 'city', 'towards', 'inferencing', 'analytics', 'big', 'data', 'daten', 'und', 'diabetes', 'big', 'data', 'medizin', 'conex', 'efficient', 'exploration', 'big', 'data', 'system', 'configuration', 'better', 'performance', 'smallholder', 'need', 'access', 'big', 'data', 'agronomy', 'jbhi', 'special', 'issue', 'big', 'data', 'health', 'risk', 'reward', 'big', 'data', 'epigenomics', 'research', 'interview', 'melanie', 'ehrlich', 'ultralow', 'power', 'memory', 'based', 'big', 'data', 'computing', 'platform', 'nonvolatile', 'domain', 'wall', 'nanowire', 'device', 'bike', 'sharing', 'system', 'big', 'data', 'perspective', 'facebook', 'fiasco', 'big', 'data', 'researcher', 'rethink', 'ethic', 'mobile', 'edge', 'computing', 'big', 'data', 'enabled', 'electric', 'vehicle', 'charging', 'comparative', 'evaluation', 'big', 'data', 'system', 'scientific', 'image', 'analytics', 'workload', 'research', 'big', 'data', 'oriented', 'cloud', 'evaluation', 'complex', 'alliance', 'new', 'energy', 'vehicle', 'political', 'depression', 'big', 'data', 'multimethod', 'investigation', 'american', 'emotional', 'response', 'trump', 'presidency', 'selbst', 'ist', 'der', 'forscher', 'big', 'data', 'analysen', 'mit', 'galaxy', 'semantic', 'interoperability', 'big', 'data', 'scale', 'open', 'opc', 'ua', 'implementation', 'semantic', 'interoperability', 'big', 'data', 'heterogeneous', 'iot', 'infrastructure', 'healthcare', 'performance', 'evaluation', 'nosql', 'big', 'data', 'application', 'using', 'multi', 'formalism', 'model', 'da', 'grosse', 'datenproblem', 'big', 'data', 'analysen', 'zur', 'strategischen', 'unternehmensausrichtung', 'abnormal', 'operation', 'tracking', 'big', 'data', 'based', 'gram', 'schmidt', 'orthogonalization', 'production', 'n', 'propyl', 'propionate', 'simulated', 'moving', 'bed', 'reactor', 'case', 'study', 'formal', 'method', 'artificial', 'intelligence', 'big', 'data', 'analytics', 'knowledge', 'engineering', 'medical', 'care', 'reduce', 'disease', 'burden', 'health', 'disparity', 'noch', 'verlaufen', 'die', 'big', 'data', 'analytics', 'projekte', 'ganz', 'anders', 'al', 'geplant', 'enhancing', 'physical', 'layer', 'security', 'via', 'big', 'data', 'aided', 'hybrid', 'relay', 'selection', 'buzzterm', 'boardroom', 'big', 'data', 'analytics', 'come', 'middleware', 'managing', 'big', 'data', 'flow', 'ari', 'caroline', 'big', 'data', 'guru', 'mine', 'analytics', 'help', 'cancer', 'patient', 'resource', 'career', 'new', 'pattern', 'lifecycle', 'big', 'data', 'driven', 'smart', 'manufacturing', 'service', 'complex', 'product', 'human', 'project', 'big', 'data', 'studie', 'startet', 'new', 'york', 'situating', 'ecology', 'big', 'data', 'science', 'current', 'advance', 'challenge', 'solution', 'brief', 'announcement', 'mending', 'big', 'data', 'missing', 'information', 'advancing', 'manufacturing', 'system', 'big', 'data', 'analytics', 'conceptual', 'framework', 'review', 'sentiment', 'discovery', 'analysis', 'educational', 'big', 'data', 'industrial', 'symbiosis', 'exploring', 'big', 'data', 'approach', 'waste', 'stream', 'discovery', 'pipelined', 'multi', 'gpu', 'mapreduce', 'big', 'data', 'processing', 'accountability', 'big', 'data', 'algorithm', 'noch', 'verlaufen', 'die', 'big', 'data', 'analytics', 'projekte', 'ganz', 'anders', 'al', 'geplant', 'editorial', 'note', 'hci', 'system', 'big', 'data', 'based', 'multimedia', 'application', 'emergency', 'drug', 'procurement', 'planning', 'based', 'big', 'data', 'driven', 'morbidity', 'prediction', 'interview', 'mit', 'stefan', 'wrobel', 'zum', 'thema', 'angewandte', 'big', 'data', 'forschung', 'physical', 'education', 'grand', 'convergence', 'fitnessgram', 'big', 'data', 'digital', 'commerce', 'child', 'health', 'deadline', 'aware', 'scheduling', 'flexible', 'bandwidth', 'allocation', 'big', 'data', 'transfer', 'ad', 'exec', 'future', 'big', 'data', 'draper', 'qualitative', 'readiness', 'requirement', 'assessment', 'model', 'enterprise', 'big', 'data', 'infrastructure', 'investment', 'position', 'synchronization', 'track', 'geometry', 'inspection', 'data', 'via', 'big', 'data', 'fusion', 'incremental', 'learning', 'structural', 'health', 'monitoring', 'big', 'data', 'problem', 'economics', 'econophysics', 'era', 'big', 'data', 'identifying', 'industrial', 'cluster', 'novel', 'big', 'data', 'methodology', 'sic', 'code', 'fit', 'purpose', 'internet', 'age', 'mapping', 'collective', 'behavior', 'big', 'data', 'era', 'code', 'offloading', 'scheme', 'big', 'data', 'processing', 'android', 'application', 'high', 'performance', 'interconnection', 'network', 'exascale', 'big', 'data', 'era', 'power', 'message', 'network', 'big', 'data', 'analysis', 'network', 'agenda', 'setting', 'model', 'issue', 'ownership', 'failure', 'analysis', 'prediction', 'big', 'data', 'system', 'linear', 'estimation', 'problem', 'information', 'big', 'data', 'system', 'phylogenomics', 'principle', 'opportunity', 'pitfall', 'big', 'data', 'phylogenetics', 'kernel', 'based', 'framework', 'medical', 'big', 'data', 'analytics', 'fast', 'algorithm', 'relaxation', 'process', 'big', 'data', 'system', 'page', 'biology', 'must', 'develop', 'big', 'data', 'system', 'jbhi', 'special', 'issue', 'x', 'c', 'big', 'data', 'health', 'x', 'starting', 'think', 'big', 'data', 'approach', 'clinical', 'detection', 'early', 'stage', 'bipolar', 'disorder', 'evidence', 'based', 'assessment', 'statistical', 'learning', 'model', 'interview', 'mit', 'michael', 'feindt', 'zum', 'thema', 'pr', 'skriptive', 'big', 'data', 'analyse', 'rw', 'application', 'artificial', 'intelligence', 'medical', 'big', 'data', 'real', 'world', 'evidence', 'generation', 'literature', 'review', 'research', 'practice', 'china', 'wichtig', 'ist', 'auch', 'der', 'hinweis', 'das', 'big', 'data', 'und', 'vergleichbare', 'konzepte', 'nicht', 'unmittelbar', 'greifen', 'symposium', 'insure', 'tech', 'digitalization', 'big', 'data', 'technique', 'risk', 'management', 'insurance', 'sieben', 'schritten', 'zum', 'erfolgreichen', 'big', 'data', 'projekt', 'big', 'data', 'big', 'opportunity', 'librarian', 'big', 'data', 'expert', 'discus', 'customer', 'data', 'treatment', 'big', 'data', 'present', 'future', 'big', 'data', 'driven', 'service', 'composition', 'using', 'parallel', 'clustered', 'particle', 'swarm', 'optimization', 'mobile', 'environment', 'big', 'data', 'element', 'good', 'question', 'open', 'data', 'powerful', 'software', 'big', 'data', 'hot', 'air', 'hot', 'topic', 'big', 'data', 'web', 'crawling', 'analysing', 'financial', 'news', 'using', 'rapidminer', 'big', 'data', 'whole', 'yotta', 'byte', 'big', 'data', 'impact', 'u', 'medical', 'industry', 'big', 'data', 'impact', 'trading', 'technology', 'big', 'data', 'web', 'crawling', 'analysing', 'financial', 'news', 'using', 'rapidminer', 'big', 'data', 'boon', 'business', 'intelligence', 'big', 'data', 'key', 'energy', 'efficiency', 'smart', 'building', 'big', 'data', 'implication', 'health', 'system', 'pharmacy', 'big', 'data', 'driven', 'strategic', 'orientation', 'international', 'marketing', 'data', 'asset', 'oil', 'gas', 'sector', 'learn', 'industry', 'big', 'data', 'big', 'data', 'trend', 'stroke', 'epidemiology', 'united', 'state', 'good', 'data', 'big', 'data', 'goldmine', 'minefield', 'big', 'data', 'driven', 'manufacturing', 'process', 'monitoring', 'quality', 'philosophy', 'big', 'data', 'breaking', 'new', 'ground', 'airway', 'research', 'big', 'data', 'f', 'r', 'einen', 'ordnungsrahmen', 'zur', 'nutzung', 'digitaler', 'gesundheitsdaten', 'pl', 'diert', 'die', 'bundes', 'rztekammer', 'big', 'data', 'revolution', 'oder', 'datenhybris', 'big', 'data', 'critical', 'question', 'sport', 'society', 'big', 'data', 'big', 'opportunity', 'petroleum', 'petrochemical', 'industry', 'big', 'data', 'guest', 'editorial', 'big', 'data', 'role', 'expanding', 'access', 'financial', 'service', 'china', 'biomedical', 'big', 'data', 'new', 'model', 'control', 'access', 'use', 'governance', 'spatiotemporal', 'data', 'adaptive', 'clustering', 'algorithm', 'intelligent', 'computational', 'technique', 'city', 'big', 'data', 'data', 'aware', 'remote', 'procedure', 'call', 'method', 'big', 'data', 'system', 'covid', 'big', 'data', 'change', 'way', 'practice', 'medicine', 'rethinking', 'data', 'driven', 'decision', 'support', 'flood', 'risk', 'management', 'big', 'data', 'age', 'finance', 'big', 'data', 'management', 'analysis', 'application', 'using', 'big', 'data', 'guide', 'implementation', 'web', 'mobile', 'adaptive', 'learning', 'platform', 'medical', 'student', 'big', 'data', 'driven', 'hr', 'practice', 'improve', 'hr', 'service', 'quality', 'innovation', 'competency', 'smes', 'wie', 'big', 'data', 'auf', 'die', 'verkettung', 'von', 'strom', 'und', 'wasser', 'durchschlagen', 'prescription', 'data', 'australia', 'useful', 'big', 'data', 'using', 'big', 'data', 'optimally', 'model', 'hydrology', 'water', 'quality', 'across', 'expansive', 'region', 'confronting', 'big', 'data', 'applying', 'confrontation', 'clause', 'government', 'data', 'collection', 'modeling', 'big', 'data', 'based', 'system', 'ontological', 'trading', 'big', 'data', 'smart', 'data', 'algorithm', 'cross', 'evaluation', 'novel', 'method', 'large', 'scale', 'survey', 'analysis', 'taming', 'big', 'data', 'implementation', 'clinical', 'use', 'case', 'driven', 'architecture', 'big', 'picture', 'big', 'data', 'big', 'data', 'approach', 'global', 'freshwater', 'mussel', 'diversity', 'bivalvia', 'unionoida', 'updated', 'checklist', 'genus', 'specie', 'using', 'big', 'data', 'co', 'innovation', 'process', 'mapping', 'field', 'data', 'driven', 'innovation', 'proposing', 'theoretical', 'development', 'providing', 'research', 'agenda', 'big', 'data', 'centric', 'architecture', 'metamodel', 'industry', 'medical', 'big', 'data', 'current', 'status', 'problem', 'trend', 'toward', 'solution', 'exploring', 'big', 'data', 'next', 'big', 'thing', 'innovation', 'digitisation', 'big', 'data', 'transformation', 'accounting', 'information', 'integrating', 'big', 'data', 'surgical', 'practice', 'scholarly', 'big', 'data', 'information', 'extraction', 'data', 'mining', 'rethinking', 'big', 'data', 'visual', 'knowledge', 'sublime', 'diagrammatic', 'data', 'visualisation', 'querying', 'big', 'data', 'bridging', 'theory', 'practice', 'big', 'data', 'enabled', 'consolidated', 'framework', 'energy', 'efficient', 'software', 'defined', 'data', 'center', 'iot', 'setup', 'humanizing', 'big', 'data', 'marketing', 'meeting', 'data', 'social', 'science', 'consumer', 'insightc', 'strong', 'london', 'kogan', 'page', 'pp', 'isbn', 'regulating', 'big', 'data', 'guideline', 'council', 'europe', 'context', 'european', 'data', 'protection', 'framework', 'big', 'data', 'business', 'strategy', 'interconnection', 'grand', 'challenge', 'knowledge', 'management', 'review', 'future', 'perspective', 'marine', 'big', 'data', 'concept', 'application', 'platform', 'construction', 'beyond', 'big', 'data', 'surveillance', 'metadata', 'technology', 'enabled', 'intelligence', 'opportunity', 'counter', 'terrorism', 'big', 'data', 'state', 'mind', 'epistemological', 'challenge', 'accountability', 'transparency', 'data', 'driven', 'regulation', 'rethink', 'big', 'european', 'roadmap', 'hardware', 'networking', 'optimization', 'big', 'data', 'rethinking', 'big', 'data', 'visual', 'knowledge', 'sublime', 'diagrammatic', 'data', 'visualisation', 'integrating', 'big', 'data', 'semantic', 'extract', 'transform', 'load', 'framework', 'big', 'data', 'based', 'worker', 'behavior', 'observation', 'china', 'metro', 'construction', 'coping', 'big', 'data', 'growing', 'pain', 'digitisation', 'big', 'data', 'transformation', 'accounting', 'information', 'big', 'data', 'approach', 'global', 'freshwater', 'mussel', 'diversity', 'bivalvia', 'unionoida', 'updated', 'checklist', 'genus', 'specie', 'open', 'data', 'prevent', 'research', 'fraud', 'promote', 'reproducibility', 'enable', 'big', 'data', 'analytics', 'clinical', 'research', 'harnessing', 'big', 'data', 'capability', 'deliver', 'result', 'feedback', 'big', 'data', 'based', 'lie', 'robot', 'integrating', 'big', 'data', 'surgical', 'practice', 'data', 'driven', 'ax', 'creation', 'model', 'correlation', 'measurement', 'big', 'data', 'analytics', 'embracing', 'big', 'data', 'redefining', 'big', 'data', 'interview', 'bill', 'inmon', 'big', 'data', 'smart', 'data', 'role', 'metabolomics', 'generating', 'actionable', 'knowledge', 'alzheimer', 'disease', 'personalized', 'treatment', 'educational', 'big', 'data', 'extracting', 'meaning', 'data', 'smart', 'education', 'big', 'data', 'make', 'big', 'impact', 'finding', 'systematic', 'review', 'longitudinal', 'case', 'study', 'geospatial', 'big', 'data', 'new', 'paradigm', 'remote', 'sensing', 'application', 'big', 'data', 'study', 'quantify', 'relationship', 'bmi', 'different', 'cancer', 'big', 'data', 'embedded', 'new', 'product', 'development', 'influence', 'project', 'success', 'harnessing', 'big', 'data', 'methodological', 'approach', 'linking', 'electronic', 'health', 'record', 'patient', 'reported', 'survey', 'data', 'taming', 'big', 'data', 'applying', 'experimental', 'method', 'naturalistic', 'data', 'set', 'architecting', 'big', 'data', 'challenge', 'study', 'forecast', 'managing', 'big', 'data', 'cloud', 'computing', 'co', 'location', 'center', 'integrating', 'big', 'data', 'aquatic', 'ecology', 'challenge', 'opportunity', 'small', 'data', 'enabled', 'prediction', 'obama', 'win', 'say', 'economist', 'big', 'data', 'crowdsourcing', 'resulted', 'complex', 'prediction', 'integrating', 'big', 'data', 'analytics', 'supply', 'chain', 'finance', 'role', 'information', 'processing', 'data', 'driven', 'culture', 'big', 'data', 'content', 'delivery', 'wireless', 'device', 'device', 'sharing', 'large', 'scale', 'mobile', 'network', 'bigger', 'data', 'big', 'data', 'twitter', 'brain', 'computer', 'interface', 'big', 'data', 'rich', 'data', 'key', 'feature', 'athlete', 'wheelchair', 'mobility', 'performance', 'prescription', 'data', 'australia', 'useful', 'big', 'data', 'solving', 'big', 'data', 'distributing', 'computation', 'among', 'smart', 'device', 'teaching', 'big', 'data', 'analysis', 'young', 'immunologist', 'demystifying', 'big', 'data', 'mandatory', 'evolution', 'forensic', 'accounting', 'brazil', 'using', 'data', 'driven', 'safety', 'decision', 'making', 'realize', 'smart', 'safety', 'management', 'era', 'big', 'data', 'theoretical', 'perspective', 'basic', 'question', 'answer', 'using', 'big', 'data', 'cost', 'effectiveness', 'analysis', 'next', 'generation', 'sequencing', 'technology', 'challenge', 'potential', 'solution', 'technology', 'big', 'data', 'search', 'benefit', 'making', 'insight', 'actionable', 'key', 'mining', 'big', 'data', 'philologist', 'perspective', 'aviation', 'community', 'beginning', 'understand', 'done', 'aircraft', 'big', 'data', 'mobile', 'big', 'data', 'fuel', 'data', 'driven', 'wireless', 'smart', 'evac', 'big', 'data', 'based', 'decision', 'making', 'emergency', 'evacuation', 'bitkom', 'beste', 'voraussetzungen', 'f', 'r', 'den', 'big', 'data', 'standort', 'deutschland', 'memory', 'tsvd', 'big', 'data', 'factorization', 'fine', 'grained', 'dynamic', 'resource', 'allocation', 'big', 'data', 'application', 'timed', 'analysis', 'big', 'data', 'application', 'evaluation', 'eines', 'zukunftsszenarios', 'zur', 'nutzung', 'von', 'big', 'data', 'anwendungen', 'f', 'r', 'die', 'verbesserung', 'der', 'versorgung', 'von', 'menschen', 'mit', 'seltenen', 'erkrankungen', 'monsanto', 'throw', 'hat', 'big', 'data', 'ring', 'ursachenforschung', 'der', 'medizin', 'mit', 'big', 'data', 'dem', 'vergessen', 'auf', 'der', 'spur', 'seeking', 'alpha', 'dividend', 'announcement', 'big', 'data', 'insight', 'joining', 'car', 'eva', 'style', 'analysis', 'randomized', 'block', 'proximal', 'method', 'distributed', 'stochastic', 'big', 'data', 'optimization', 'china', 'kidney', 'disease', 'network', 'ck', 'net', 'big', 'data', 'big', 'dream', 'predicting', 'pattern', 'technology', 'convergence', 'using', 'big', 'data', 'technology', 'large', 'scale', 'triadic', 'patent', 'globeland', 'operational', 'global', 'land', 'cover', 'mapping', 'big', 'data', 'analysis', 'pwr', 'pin', 'ho

In [18]:
count = Counter(words2)
count

Counter({'big': 1126,
         'data': 1272,
         'analytics': 69,
         'method': 24,
         'capturing': 2,
         'visitor': 1,
         'activity': 4,
         'flow': 6,
         'case': 16,
         'island': 1,
         'country': 1,
         'ecology': 4,
         'approach': 49,
         'lead': 1,
         'increased': 2,
         'understanding': 8,
         'animal': 1,
         'movement': 1,
         'analysis': 85,
         'disaster': 4,
         'information': 29,
         'dissemination': 2,
         'south': 2,
         'korea': 2,
         'real': 21,
         'world': 20,
         'study': 28,
         'laboratory': 5,
         'medicine': 17,
         'current': 7,
         'status': 5,
         'application': 42,
         'future': 20,
         'consideration': 3,
         'der': 17,
         'kunde': 1,
         'clinical': 15,
         'based': 90,
         'design': 9,
         'glut': 1,
         'targeted': 2,
         'carbon': 3,
         'nanodots': 1,
         'accurate': 4,
         'diagnosis': 6,
         'hepatocellular': 1,
         'carcinomaelectronic': 1,
         'supplementary': 1,
         'esi': 1,
         'available': 2,
         'see': 1,
         'doi': 2,
         'http': 1,
         'org': 1,
         'nr': 1,
         'j': 1,
         'mandola': 1,
         'processing': 13,
         'visualization': 6,
         'platform': 28,
         'monitoring': 12,
         'detecting': 1,
         'online': 9,
         'hate': 1,
         'speech': 1,
         'cloud': 20,
         'driven': 84,
         'dynamic': 7,
         'control': 12,
         'unmanned': 2,
         'ground': 3,
         'vehicle': 9,
         'safety': 11,
         'improving': 3,
         'distributed': 8,
         'partitioned': 1,
         'optimization': 20,
         'via': 5,
         'asynchronous': 1,
         'dual': 2,
         'decomposition': 1,
         'tensor': 2,
         'routing': 1,
         'recommendation': 6,
         'heterogeneous': 5,
         'network': 24,
         'leveraging': 7,
         'revolution': 17,
         'cm': 1,
         'expanding': 3,
         'capability': 7,
         'spur': 2,
         'health': 36,
         'system': 54,
         'transformation': 9,
         'editorial': 9,
         'advanced': 6,
         'tool': 5,
         'high': 11,
         'throughput': 3,
         'omics': 2,
         'technology': 31,
         'four': 1,
         'illustrate': 1,
         'potential': 10,
         'shared': 1,
         'national': 4,
         'multipurpose': 1,
         'ibm': 1,
         'stellt': 1,
         'service': 20,
         'au': 3,
         'twitter': 2,
         'vor': 1,
         'traditional': 5,
         'v': 3,
         'fashion': 1,
         'trend': 11,
         'forecasting': 8,
         'examination': 2,
         'using': 52,
         'wgsn': 1,
         'edited': 2,
         'optimizing': 3,
         'read': 1,
         'enlightenment': 1,
         'era': 34,
         'research': 43,
         'tcm': 1,
         'acupuncture': 1,
         'comprehensive': 1,
         'yield': 1,
         'enhancement': 1,
         'semiconductor': 1,
         'manufacturing': 11,
         'genomics': 4,
         'precision': 6,
         'lesson': 4,
         'project': 7,
         'hybrid': 3,
         'tolerance': 1,
         'estimate': 1,
         'environmental': 6,
         'benefit': 6,
         'electric': 5,
         'bike': 3,
         'sharing': 9,
         'st': 1,
         'century': 1,
         'investing': 1,
         'company': 9,
         'soaring': 1,
         'despite': 1,
         'price': 5,
         'still': 3,
         'possible': 2,
         'cash': 1,
         'proactive': 1,
         'emerging': 4,
         'paradigm': 4,
         'mining': 16,
         'vermeidern': 1,
         'verringern': 1,
         'verbessern': 1,
         'analysen': 4,
         'al': 3,
         'alternative': 2,
         'zu': 2,
         'tierversuchen': 1,
         'simd': 1,
         'parallel': 4,
         'mcmc': 1,
         'sampling': 2,
         'bayesian': 2,
         'integrative': 1,
         'biology': 4,
         'centrism': 1,
         'mapping': 7,
         'bioscience': 1,
         'ethic': 3,
         'perspective': 17,
         'w': 2,
         'matrix': 2,
         'pmu': 3,
         'medical': 16,
         'evidence': 7,
         'generation': 11,
         'practice': 16,
         'post': 2,
         'marketing': 9,
         'china': 15,
         'implementation': 7,
         'spark': 1,
         'distribution': 5,
         'interception': 1,
         'performance': 22,
         'solution': 13,
         'gwas': 1,
         'point': 2,
         'intelligenz': 2,
         'contra': 1,
         'chaos': 2,
         'framework': 25,
         'aligning': 1,
         'strategy': 11,
         'organizational': 3,
         'goal': 3,
         'career': 2,
         'graduate': 2,
         'program': 1,
         'analyst': 1,
         'availability': 1,
         'geo': 1,
         'computing': 14,
         'cover': 3,
         'putting': 3,
         'pressure': 2,
         'storage': 5,
         'israeli': 1,
         'firm': 4,
         'medaware': 1,
         'offer': 6,
         'software': 7,
         'help': 6,
         'detect': 2,
         'prescription': 3,
         'error': 4,
         'science': 31,
         'backwards': 1,
         'methodology': 3,
         'time': 17,
         'sustainability': 1,
         'smart': 28,
         'city': 6,
         'towards': 7,
         'inferencing': 1,
         'daten': 2,
         'und': 13,
         'diabetes': 2,
         'medizin': 3,
         'conex': 1,
         'efficient': 9,
         'exploration': 2,
         'configuration': 1,
         'better': 3,
         'smallholder': 2,
         'need': 8,
         'access': 7,
         'agronomy': 1,
         'jbhi': 2,
         'special': 9,
         'issue': 23,
         'risk': 13,
         'reward': 3,
         'epigenomics': 1,
         'interview': 4,
         'melanie': 1,
         'ehrlich': 1,
         'ultralow': 1,
         'power': 11,
         'memory': 5,
         'nonvolatile': 3,
         'domain': 3,
         'wall': 1,
         'nanowire': 1,
         'device': 10,
         'facebook': 1,
         'fiasco': 1,
         'researcher': 5,
         'rethink': 2,
         'mobile': 10,
         'edge': 3,
         'enabled': 9,
         'charging': 3,
         'comparative': 2,
         'evaluation': 7,
         'scientific': 5,
         'image': 3,
         'workload': 3,
         'oriented': 6,
         'complex': 6,
         'alliance': 1,
         'new': 49,
         'energy': 22,
         'political': 5,
         'depression': 1,
         'multimethod': 1,
         'investigation': 2,
         'american': 1,
         'emotional': 1,
         'response': 2,
         'trump': 1,
         'presidency': 1,
         'selbst': 1,
         'ist': 4,
         'forscher': 1,
         'mit': 7,
         'galaxy': 1,
         'semantic': 5,
         'interoperability': 2,
         'scale': 9,
         'open': 9,
         'opc': 1,
         'ua': 1,
         'iot': 17,
         'infrastructure': 8,
         'healthcare': 11,
         'nosql': 2,
         'multi': 5,
         'formalism': 1,
         'model': 41,
         'da': 2,
         'grosse': 1,
         'datenproblem': 1,
         'zur': 5,
         'strategischen': 1,
         'unternehmensausrichtung': 1,
         'abnormal': 2,
         'operation': 4,
         'tracking': 4,
         'gram': 1,
         'schmidt': 1,
         'orthogonalization': 1,
         'production': 5,
         'n': 1,
         'propyl': 1,
         'propionate': 1,
         'simulated': 1,
         'moving': 6,
         'bed': 1,
         'reactor': 1,
         'formal': 2,
         'artificial': 4,
         'intelligence': 19,
         'knowledge': 11,
         'engineering': 6,
         'care': 10,
         'reduce': 2,
         'disease': 12,
         'burden': 1,
         'disparity': 1,
         'noch': 3,
         'verlaufen': 2,
         'die': 12,
         'projekte': 2,
         'ganz': 2,
         'anders': 2,
         'geplant': 2,
         'enhancing': 2,
         'physical': 3,
         'layer': 1,
         'security': 9,
         'aided': 1,
         'relay': 1,
         'selection': 3,
         'buzzterm': 1,
         'boardroom': 1,
         'come': 4,
         'middleware': 1,
         'managing': 5,
         'ari': 1,
         'caroline': 1,
         'guru': 1,
         'mine': 2,
         'cancer': 6,
         'patient': 15,
         'resource': 4,
         'pattern': 10,
         'lifecycle': 1,
         'product': 7,
         'human': 11,
         'studie': 2,
         'startet': 1,
         'york': 2,
         'situating': 1,
         'advance': 5,
         'challenge': 53,
         'brief': 1,
         'announcement': 2,
         'mending': 1,
         'missing': 2,
         'advancing': 1,
         'conceptual': 3,
         'review': 20,
         'sentiment': 2,
         'discovery': 9,
         'educational': 3,
         'industrial': 6,
         'symbiosis': 1,
         'exploring': 5,
         'waste': 2,
         'stream': 3,
         'pipelined': 1,
         'gpu': 3,
         'mapreduce': 2,
         'accountability': 2,
         'algorithm': 21,
         'note': 1,
         'hci': 1,
         'multimedia': 3,
         'emergency': 2,
         'drug': 8,
         'procurement': 1,
         'planning': 7,
         'morbidity': 1,
         'prediction': 20,
         'stefan': 1,
         'wrobel': 1,
         'zum': 3,
         'thema': 2,
         'angewandte': 1,
         'forschung': 1,
         'education': 8,
         'grand': 2,
         'convergence': 3,
         'fitnessgram': 1,
         'digital': 16,
         'commerce': 2,
         'child': 5,
         'deadline': 3,
         'aware': 4,
         'scheduling': 9,
         'flexible': 2,
         'bandwidth': 1,
         'allocation': 3,
         'transfer': 2,
         'ad': 2,
         'exec': 1,
         'draper': 1,
         'qualitative': 3,
         'readiness': 1,
         'requirement': 2,
         'assessment': 9,
         'enterprise': 7,
         'investment': 1,
         'position': 2,
         'synchronization': 1,
         'track': 1,
         'geometry': 1,
         'inspection': 1,
         'fusion': 4,
         'incremental': 2,
         'learning': 30,
         'structural': 2,
         'problem': 10,
         'economics': 1,
         'econophysics': 2,
         'identifying': 2,
         'cluster': 5,
         'novel': 10,
         'sic': 1,
         'code': 2,
         'fit': 3,
         'purpose': 2,
         'internet': 10,
         'age': 7,
         'collective': 1,
         'behavior': 9,
         'offloading': 1,
         'scheme': 3,
         'android': 1,
         'interconnection': 3,
         'exascale': 2,
         'message': 3,
         'agenda': 3,
         'setting': 1,
         'ownership': 3,
         'failure': 2,
         'linear': 1,
         'estimation': 6,
         'phylogenomics': 1,
         'principle': 1,
         'opportunity': 31,
         'pitfall': 3,
         'phylogenetics': 2,
         'kernel': 2,
         'fast': 2,
         'relaxation': 1,
         'process': 21,
         'page': 3,
         'must': 2,
         'develop': 1,
         'x': 4,
         'c': 3,
         'starting': 2,
         'think': 9,
         'detection': 6,
         'early': 2,
         'stage': 2,
         'bipolar': 1,
         'disorder': 1,
         'statistical': 6,
         'michael': 1,
         'feindt': 1,
         'pr': 2,
         'skriptive': 1,
         'analyse': 3,
         'rw': 1,
         'literature': 3,
         'wichtig': 1,
         'auch': 2,
         'hinweis': 1,
         'das': 1,
         'vergleichbare': 1,
         'konzepte': 1,
         'nicht': 1,
         'unmittelbar': 1,
         'greifen': 1,
         'symposium': 2,
         'insure': 1,
         'tech': 1,
         'digitalization': 1,
         'technique': 11,
         'management': 28,
         'insurance': 1,
         'sieben': 1,
         'schritten': 1,
         'erfolgreichen': 1,
         'projekt': 1,
         'librarian': 3,
         'expert': 3,
         'discus': 3,
         'customer': 7,
         'treatment': 6,
         'present': 1,
         'composition': 1,
         'clustered': 2,
         'particle': 1,
         'swarm': 1,
         'environment': 7,
         'element': 1,
         'good': 5,
         'question': 9,
         'powerful': 1,
         'hot': 2,
         'air': 5,
         'topic': 2,
         'web': 4,
         'crawling': 2,
         'analysing': 2,
         'financial': 6,
         'news': 3,
         'rapidminer': 2,
         'whole': 1,
         'yotta': 1,
         'byte': 1,
         'impact': 18,
         'u': 10,
         'industry': 17,
         'trading': 2,
         'boon': 2,
         'business': 20,
         'key': 7,
         'efficiency': 6,
         'building': 7,
         'implication': 8,
         'pharmacy': 1,
         'strategic': 3,
         'orientation': 1,
         'international': 3,
         'asset': 5,
         'oil': 5,
         'gas': 2,
         'sector': 5,
         'learn': 2,
         'stroke': 2,
         'epidemiology': 6,
         'united': 5,
         'state': 14,
         'goldmine': 1,
         'minefield': 1,
         'quality': 11,
         'philosophy': 3,
         'breaking': 1,
         'airway': 1,
         'f': 10,
         'r': 13,
         'einen': 1,
         'ordnungsrahmen': 1,
         'nutzung': 2,
         'digitaler': 2,
         'gesundheitsdaten': 1,
         'pl': 1,
         'diert': 1,
         'bundes': 1,
         'rztekammer': 1,
         'oder': 1,
         'datenhybris': 1,
         'critical': 6,
         'sport': 3,
         'society': 2,
         'petroleum': 1,
         'petrochemical': 1,
         'guest': 4,
         'role': 10,
         'biomedical': 2,
         'use': 23,
         'governance': 5,
         'spatiotemporal': 2,
         'adaptive': 7,
         'clustering': 6,
         'intelligent': 13,
         'computational': 7,
         'remote': 4,
         'procedure': 1,
         'call': 7,
         'covid': 7,
         'change': 3,
         'way': 8,
         'rethinking': 5,
         'decision': 21,
         'support': 6,
         'flood': 3,
         'finance': 2,
         'guide': 3,
         'student': 6,
         'hr': 2,
         'improve': 11,
         'innovation': 12,
         'competency': 1,
         'smes': 1,
         'wie': 3,
         'auf': 4,
         'verkettung': 2,
         'von': 10,
         'strom': 2,
         'wasser': 2,
         'durchschlagen': 2,
         'australia': 2,
         'useful': 2,
         'optimally': 1,
         'hydrology': 1,
         'water': 4,
         'across': 3,
         'expansive': 1,
         'region': 3,
         'confronting': 1,
         'applying': 5,
         'confrontation': 1,
         'clause': 1,
         'government': 7,
         'collection': 2,
         'modeling': 13,
         'ontological': 1,
         'cross': 4,
         'large': 17,
         'survey': 12,
         'taming': 3,
         'architecture': 10,
         'picture': 2,
         'global': 7,
         'freshwater': 2,
         'mussel': 2,
         'diversity': 3,
         'bivalvia': 2,
         'unionoida': 2,
         'updated': 2,
         'checklist': 2,
         'genus': 2,
         'specie': 2,
         'co': 3,
         'field': 8,
         'proposing': 1,
         'theoretical': 5,
         'development': 10,
         'providing': 1,
         'centric': 1,
         'metamodel': 1,
         'toward': 8,
         'next': 11,
         'thing': 7,
         'digitisation': 3,
         'accounting': 6,
         'integrating': 6,
         'surgical': 2,
         'scholarly': 2,
         'extraction': 3,
         'visual': 8,
         'sublime': 3,
         'diagrammatic': 3,
         'visualisation': 3,
         'querying': 1,
         'bridging': 3,
         'theory': 4,
         'consolidated': 1,
         'defined': 1,
         'center': 7,
         'setup': 1,
         'humanizing': 2,
         'meeting': 2,
         'social': 26,
         'consumer': 3,
         'insightc': 1,
         'strong': 2,
         'london': 3,
         'kogan': 2,
         'pp': 6,
         'isbn': 6,
         'regulating': 1,
         'guideline': 3,
         'council': 2,
         'europe': 2,
         'context': 8,
         'european': 2,
         'protection': 4,
         'marine': 2,
         'concept': 7,
         'construction': 2,
         'beyond': 6,
         'surveillance': 2,
         'metadata': 3,
         'counter': 1,
         'terrorism': 1,
         'mind': 1,
         'epistemological': 1,
         'transparency': 1,
         'regulation': 1,
         'roadmap': 1,
         'hardware': 2,
         'networking': 7,
         'extract': 2,
         'transform': 10,
         'load': 1,
         'worker': 3,
         'observation': 3,
         'metro': 1,
         'coping': 3,
         'growing': 2,
         'pain': 4,
         'prevent': 2,
         'fraud': 1,
         'promote': 2,
         'reproducibility': 1,
         'enable': 3,
         'harnessing': 5,
         'deliver': 1,
         'result': 2,
         'feedback': 2,
         'lie': 1,
         'robot': 1,
         'ax': 1,
         'creation': 2,
         'correlation': 4,
         'measurement': 8,
         'embracing': 1,
         'redefining': 1,
         'bill': 1,
         'inmon': 1,
         'metabolomics': 1,
         'generating': 1,
         'actionable': 2,
         'alzheimer': 4,
         'personalized': 5,
         'extracting': 1,
         'meaning': 3,
         'make': 7,
         'finding': 4,
         'systematic': 2,
         'longitudinal': 1,
         'geospatial': 2,
         'sensing': 6,
         'quantify': 2,
         'relationship': 7,
         'bmi': 1,
         'different': 4,
         'embedded': 1,
         'influence': 2,
         'success': 2,
         'methodological': 4,
         'linking': 2,
         'electronic': 1,
         'record': 2,
         'reported': 2,
         'experimental': 1,
         'naturalistic': 1,
         'set': 4,
         'architecting': 2,
         'forecast': 1,
         'location': 2,
         'aquatic': 1,
         'small': 22,
         'obama': 1,
         'win': 1,
         'say': 3,
         'economist': 1,
         'crowdsourcing': 2,
         'resulted': 1,
         'supply': 7,
         'chain': 6,
         'culture': 4,
         'content': 4,
         'delivery': 2,
         'wireless': 7,
         'bigger': 5,
         'brain': 3,
         'computer': 1,
         'interface': 1,
         'rich': 2,
         'feature': 7,
         'athlete': 1,
         'wheelchair': 1,
         'mobility': 5,
         'solving': 2,
         'distributing': 1,
         'computation': 3,
         'among': 4,
         'teaching': 1,
         'young': 1,
         'immunologist': 1,
         'demystifying': 3,
         'mandatory': 1,
         'evolution': 6,
         'forensic': 1,
         'brazil': 1,
         'making': 22,
         'realize': 2,
         'basic': 2,
         'answer': 3,
         'cost': 5,
         'effectiveness': 2,
         'sequencing': 3,
         'search': 3,
         'insight': 8,
         'philologist': 1,
         'aviation': 1,
         'community': 5,
         'beginning': 4,
         'understand': 1,
         'done': 1,
         'aircraft': 3,
         'fuel': 1,
         'evac': 1,
         'evacuation': 1,
         'bitkom': 1,
         'beste': 1,
         'voraussetzungen': 1,
         'den': 1,
         'standort': 1,
         'deutschland': 1,
         'tsvd': 1,
         'factorization': 1,
         'fine': 3,
         'grained': 1,
         'timed': 1,
         'eines': 1,

In [19]:
word_count = dict()

for tag, counts in count.most_common(50):
  if(len(str(tag))>1):
    word_count[tag] = counts
    print("%s : %d" % (tag, counts))

data : 1272
big : 1126
based : 90
analysis : 85
driven : 84
analytics : 69
system : 54
challenge : 53
using : 52
approach : 49
new : 49
research : 43
application : 42
model : 41
health : 36
era : 34
technology : 31
science : 31
opportunity : 31
learning : 30
information : 29
study : 28
platform : 28
smart : 28
management : 28
social : 26
framework : 25
method : 24
network : 24
issue : 23
use : 23
performance : 22
energy : 22
small : 22
making : 22
real : 21
algorithm : 21
process : 21
decision : 21
world : 20
future : 20
cloud : 20
optimization : 20
service : 20
review : 20
prediction : 20
business : 20
intelligence : 19
impact : 18
medicine : 17